version: '3.8'

services:
  security:
    build: .
    restart: always
    image: images-s
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: security_jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: 21072003
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 21072003
      MYSQL_DATABASE: security_jwt
      MYSQL_USER: root
      MYSQL_PASSWORD: 21072003
    ports:
      - "3307:3306"
