version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=21072003
      - MYSQL_DATABASE=security_jwt
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3307:3306"
  security:
    build: .
    restart: always
    image: images-s
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

